### ISSUE TITLE
throws my exception in callback

### ISSUE THREAD

**Issue by Paul75** [toukea/android-IstatSms#2]
Hello,

I want to throws exception and return a message ti the function that call. When I do this ?

`private void sendSms (String message, String address) {
        try {
            new MessagesManager(this).sendSMS(message , address);
        }
        catch (SmsException e) {
            //DO A MESSAGE
        }
    }`

SmsException is my own class

And after in the MessageManager : 
`public void sendSMS(String message, String address) throws SmsException {
        SmsSender sender = new SmsSender(this.context);
        sender.sendSms(address, message, new SmsSender.SendCallBack(){
            @Override
            public void onSuccessSending(Sms sms) {
                //when Sms has been sent successfully.
            }

            @Override
            public void onGenericFail(Sms sms) {
                //when Generic Error, ex: no enougth mobile credit.
               throw new SmsException("when Generic Error, ex: no enougth mobile credit");
            }

            @Override
            public void onRadioOffFail(Sms sms) {
                //when error due to mobile network.
            }

            @Override
            public void onBadFormedSmsFail(Sms sms) {
                //when sms is bad formed ex: not correct phone number
            }
        });
    }`

But have a error : "Unhandled exception"..

Thanks

**Comment by toukea** [comment]
yes, of course.  "Unhandled exception"
because calling sender.sendSms(.... 
and SendCallback notification method is asynchronous. so when method  '**sendSms**' is called, your code continue his execution until Android SmsManager notify sms state to IstatSms-library which transfert this response to the main thread of your app using SendCallback; so if some Exception happend inside SendCallback it will be executed in the app main thread. and your app will be broken.

fine?

**Comment by Paul75** [comment]
Oki I understant. I can't do this I only appear a Toast if error ....

**Comment by toukea** [comment]
yes you can execture any method that  you had planned to execute in case of your **SmsException**  in SendCallback given method.

B-)

**Comment by Paul75** [comment]
Thanks for help.
